package taskou.optataskprj;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TaskAssigningSolution implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public TaskAssigningSolution() {
    }

}