package taskou;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AbstractPersistable implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public AbstractPersistable() {
    }

}